#!/bin/sh
apt-get update -y && apt-get upgrade -y
cd /opt
git clone --recurse-submodules https://github.com/cobbr/Covenant
dotnet build
cd Covenant/Data
openssl genrsa 4096 > private.pem
openssl req -x509 -new -key private.pem -out public.pem
openssl pkcs12 -export -in public.pem -inkey private.pem -out covenant-dev-private.pfx
openssl x509 -pubkey -outform der -in public.pem -out covenant-dev-public.cer
rm ./Data/public.pem
rm ./Data/private.pem
cd /opt
git clone https://github.com/byt3bl33d3r/SILENTTRINITY
apt update -y && apt upgrade -y  
apt install python3.7 python3.7-dev python3-pip
sudo -H pip3 install -U pipenv
cd /opt/SILENTTRINITY/  
pip3 install -r requirements.txt
pipenv install && pipenv shell
exit 
cd /opt
sudo git clone https://github.com/BC-SECURITY/Empire.git
cd Empire
sudo ./setup/install.sh
cd /opt
sudo wget https://github.com/BC-SECURITY/Starkiller/releases/download/v1.8.0/starkiller-1.8.0.AppImage
sudo chmod +x starkiller-1.0.0.AppImage
cd /opt
curl -sSL https://raw.githubusercontent.com/nettitude/PoshC2/master/Install.sh | bash
apt install golang -y
mkdir /opt/merlin
cd /opt/merlin
wget https://github.com/Ne0nd0g/merlin/releases/download/v0.8.0/merlinServer-Linux-x64-v0.8.0.BETA.7z
7z x merlinServer-Linux-x64-v0.8.0.BETA.7z
apt-get update -y && apt-get upgrade -y
reboot now
